"""Render a ReasoningTrace into a Markdown post-mortem - the agent's deliverable."""

from __future__ import annotations

from datetime import datetime, timezone

from .agent import ReasoningTrace


def to_markdown(trace: ReasoningTrace) -> str:
    inc = trace.incident
    lines = [
        f"# Post-Mortem - {inc['id']}: {inc['title']}",
        "",
        f"*Generated by IncidentIQ on {datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC}*",
        "",
        "## Summary",
        inc["summary"],
        "",
        "## Root Cause",
        trace.root_cause,
        "",
        "## How IncidentIQ reasoned to it",
    ]
    for h in trace.hypotheses:
        mark = {"kept": "KEPT", "eliminated": "ELIMINATED", "open": "OPEN"}[h.verdict]
        lines.append(f"- **[{mark}]** {h.statement}")
        if h.reasoning:
            lines.append(f"  - {h.reasoning}")
        for ev in h.evidence:
            lines.append(f"  - evidence: {ev}")
    lines += [
        "",
        "## Immediate Mitigation",
        trace.mitigation,
        "",
        "## Durable Fix",
        trace.durable_fix,
    ]
    if trace.citations:
        lines += ["", "## Grounded sources (Foundry IQ)"]
        for c in trace.citations:
            citation = c.get("citation", "?")
            source = c.get("source", "")
            lines.append(f"- **{citation}** - {source}")
    lines += ["", "## Evidence Trail (tool calls)"]
    for tc in trace.tool_calls:
        lines.append(f"- `{tc['tool']}({tc['args']})`")
    return "\n".join(lines) + "\n"
